services:
  moeflow-mongodb:
    ports:
      - 127.0.0.1:27017:27017

  moeflow-rabbitmq:
    ports:
      - 127.0.0.1:5672:5672 # AMQP
      - 127.0.0.1:15672:15672 # management UI

  mongo-gui:
    image: ugleiton/mongo-gui
    restart: unless-stopped
    ports:
      - "4321:4321"
    environment:
      MONGO_URL: mongodb://${MONGODB_USER}:${MONGODB_PASS}@moeflow-mongodb:27017/moeflow?authSource=admin
    logging:
      driver: none
    attach: false

  moeflow-backend:
    build: ../moeflow-backend  # for local dev
    ports:
      - 127.0.0.1:5000:5000
    # TODO: should prepend `pip install` to gunicorn ?
    command: gunicorn -t 120 -w 1 --reload -b 0.0.0.0:5000 --log-level=DEBUG "app:create_app()"
    # environment:
    #   LOG_LEVEL: DEBUG
    volumes:
      - ../moeflow-backend:/app # gets merged with docker-compose.yml

  moeflow-backend-init:
    command: python3 manage.py migrate

  moeflow-celery-default:
    command: celery --app app.celery worker --queues default --hostname celery.default --loglevel=debug

  moeflow-celery-output:
    command: celery --app app.celery worker --queues output --hostname celery.output --loglevel=debug
